server:
  port: 2583

spring:
  application:
    name: spring-cloud-config

  # spring cloud security
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xmuhailong/BASE_Config_Service.git
          username: xmuhailong
          password: hailong@123
          # auth to scan directory dev and prd
          search-paths: dev, apigateway, authentication, zipkin

# register
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server01:2581/eureka, http://eureka-server02:2582/eureka

# after springboot 2.0, when use /refresh,you need security this
#management:
 # endpoints:
  #  web:
   #   exposure:
   #     include: bus-refresh