server:
  port: 2585

security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
#      client-id: client1
#      client-secret: client1
    resource:
      user-info-uri: http://localhost:${server.port}/auth/api/user
      prefer-token-info: false

#  开启所有暴露端点: /routes端点 和 /bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  ConnectTimeout: 10000 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
hystrix:
  command:
    timeoutInMilliseconds: 60000 # 设置hystrix的超时时间为6000ms

# 增加路由规则的配置
# 通过zuul.routes.<route>.path和zuul.routes.<route>.url进行配置，<route>为路由的名字，可以任意指定，但是一组path和url的路由名要相同
#如下面的例子：所有满足/api-a/** 规则的访问都会被路由转发到//localhost:9001的地址
#也就是说，我们访问http://localhost:5555/api-a/hello的时候，API网关服务就会将该请#求路由到 http://localhost:9001/hello提供的微服务接口上
zuul:
  sensitive-headers: Cookie,Set-Cookie
  # 关闭服务自动创建路由规则，必须要如下配置才可以
  ignored-services: '*'
  # prefix: /api
  routes:
    # authentication-service
    auth:
      path: /auth/**
      #敏感头信息
      sensitiveHeaders:
      # 使用service-id代替url
      service-id: authentication-service

    # meetingroom
    meetingroom:
      path: /meetingroom/**
      #敏感头信息
      sensitiveHeaders:
      # 使用service-id代替url
      service-id: meetingroom

