

server:
  port: 2662

security:
  oauth2:
    resource:
#      id: meetingroom # 这里设置其实没什么用，设置后也是默认的 oauth2-server
      user-info-uri: http://localhost:2585/auth/api/user #验证传入的令牌

spring:
  application:
    name: meetingroom
